// <auto-generated />
using System;
using AuthzEntitlements.Entitlements.Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuthzEntitlements.Entitlements.Service.Migrations
{
    [DbContext(typeof(EntitlementsDbContext))]
    [Migration("20260703171618_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-rc.1.25451.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuthzEntitlements.Entitlements.Service.Domain.Plan", b =>
                {
                    b.Property<string>("Tier")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("SeatLimit")
                        .HasColumnType("integer");

                    b.HasKey("Tier");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("AuthzEntitlements.Entitlements.Service.Domain.PlanModule", b =>
                {
                    b.Property<string>("PlanTier")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ModuleKey")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("PlanTier", "ModuleKey");

                    b.ToTable("PlanModules");
                });

            modelBuilder.Entity("AuthzEntitlements.Entitlements.Service.Domain.PlanQuota", b =>
                {
                    b.Property<string>("PlanTier")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("QuotaKey")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("Limit")
                        .HasColumnType("bigint");

                    b.HasKey("PlanTier", "QuotaKey");

                    b.ToTable("PlanQuotas");
                });

            modelBuilder.Entity("AuthzEntitlements.Entitlements.Service.Domain.SeatAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId", "UserId")
                        .IsUnique();

                    b.ToTable("SeatAssignments");
                });

            modelBuilder.Entity("AuthzEntitlements.Entitlements.Service.Domain.TenantSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PlanTier")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TenantCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantCode")
                        .IsUnique();

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("AuthzEntitlements.Entitlements.Service.Domain.UsageCounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PeriodKey")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("QuotaKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TenantCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("Used")
                        .HasColumnType("bigint");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TenantCode", "QuotaKey", "PeriodKey")
                        .IsUnique();

                    b.ToTable("UsageCounters");
                });

            modelBuilder.Entity("AuthzEntitlements.Entitlements.Service.Domain.PlanModule", b =>
                {
                    b.HasOne("AuthzEntitlements.Entitlements.Service.Domain.Plan", "Plan")
                        .WithMany("Modules")
                        .HasForeignKey("PlanTier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("AuthzEntitlements.Entitlements.Service.Domain.PlanQuota", b =>
                {
                    b.HasOne("AuthzEntitlements.Entitlements.Service.Domain.Plan", "Plan")
                        .WithMany("Quotas")
                        .HasForeignKey("PlanTier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("AuthzEntitlements.Entitlements.Service.Domain.SeatAssignment", b =>
                {
                    b.HasOne("AuthzEntitlements.Entitlements.Service.Domain.TenantSubscription", "Subscription")
                        .WithMany("Seats")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("AuthzEntitlements.Entitlements.Service.Domain.Plan", b =>
                {
                    b.Navigation("Modules");

                    b.Navigation("Quotas");
                });

            modelBuilder.Entity("AuthzEntitlements.Entitlements.Service.Domain.TenantSubscription", b =>
                {
                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
